name: 备份软件包
on:
  workflow_dispatch:
  schedule:
   - cron: 0 0 */1 * *

env:
  TZ: Asia/Shanghai

jobs:
  del_runs:
    runs-on: Ubuntu-24.04
    name: 拉取最新源码
    
    steps:
    - name: 准备阶段
      uses: actions/checkout@v2
      
    - name: 部署环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update > /dev/null 2>&1
        sudo -E apt-get -qq install -y git subversion git-core wget curl grep > /dev/null 2>&1
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
          
    - name: 整理文件
      run: |
        cd $GITHUB_WORKSPACE
        echo "下载 passwall"
        git clone -b main https://github.com/xiaorouji/openwrt-passwall-packages.git passwall
        echo "下载 passwall1"
        git clone -b main https://github.com/xiaorouji/openwrt-passwall.git passwall1
        echo "下载 passwall2"
        git clone -b main https://github.com/xiaorouji/openwrt-passwall2.git passwall2
        echo "下载 sundaqiang"
        git clone -b master https://github.com/sundaqiang/openwrt-packages.git sundaqiang
        #echo "下载 r8168"
        #git clone -b master https://github.com/BROBIRD/openwrt-r8168 r8168
        #echo "下载 dockerman"
        #git clone -b master https://github.com/lisaac/luci-app-dockerman.git dockerman
        echo "下载 rebootschedule"
        git clone -b main https://github.com/DevOpenWRT-Router/luci-app-rebootschedule.git rebootschedule
        echo "下载 unblockneteasemusic"
        git clone -b master https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic.git unblockneteasemusic
        echo "下载 self"
        git clone -b main https://github.com/${{github.repository}}.git openwrt
        echo "整理 项目"
        rm -rf ./passwall/.github
        rm -rf ./passwall/pdnsd-alt
        rm -rf ./sundaqiang/.github
        rm -rf ./sundaqiang/img
        rm -rf ./sundaqiang/README.md
        #rm -rf ./dockerman/.github
        rm -rf ./rebootschedule/.github
        rm -rf ./unblockneteasemusic/.github
        rm -rf ./openwrt/luci
        rm -rf ./openwrt/packages
        mkdir -p ./openwrt/luci
        mkdir -p ./openwrt/luci/applications
        mkdir -p ./openwrt/packages
        mv -f ./passwall1/luci-app-passwall ./openwrt/luci/applications/luci-app-passwall
        mv -f ./passwall2/luci-app-passwall2 ./openwrt/luci/applications/luci-app-passwall2
        mv -f ./passwall/* ./openwrt/packages/
        #mv -f ./r8168 ./openwrt/packages/
        mv -f ./sundaqiang/* ./openwrt/luci/applications/
        #mv -f ./dockerman/applications/luci-app-dockerman ./openwrt/luci/applications/
        mkdir -p ./openwrt/luci/applications/luci-app-rebootschedule
        mv -f ./rebootschedule/* ./openwrt/luci/applications/luci-app-rebootschedule/
        chmod 755 ./openwrt/luci/applications/luci-app-rebootschedule/root/etc/init.d/rebootschedule
        sed -i "/firstchild/d" ./openwrt/luci/applications/luci-app-rebootschedule/luasrc/controller/rebootschedule.lua
        sed -i "s/\"control\"/\"services\"/g; s/Timing setting/定时任务/g" ./openwrt/luci/applications/luci-app-rebootschedule/luasrc/controller/rebootschedule.lua
        mkdir -p ./openwrt/luci/applications/luci-app-unblockneteasemusic
        mv -f ./unblockneteasemusic/* ./openwrt/luci/applications/luci-app-unblockneteasemusic/
    - name: 上传仓库
      run: |
        echo "上传我的仓库"
        cd $GITHUB_WORKSPACE
        cd openwrt
        git add .
        git commit -m "Sync OpenwrtPackagesBackup on $(date +%Y-%m-%d-%H-%M-%S)"
        echo "开始上传${{github.repository}}!"
        git push --quiet "https://${{ secrets.REPO_TOKEN }}@github.com/${{github.repository}}" HEAD:main
        echo "同步完成!"

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 7
        keep_minimum_runs: 7
